#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
# echo "Hello Word!" > /etc/nginx/html/index.html
echo "Hello Word!" | sudo tee /etc/nginx/html/index.html > /dev/null
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://google.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
