#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
# echo "Hello Word!" > /etc/nginx/html/index.html
echo "Hello Word!" | sudo tee /etc/nginx/html/index.html > /dev/null
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://www.google.com;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
