#!/usr/bin/env bash
# Configure Nginx  HTTP response contains a custom header
# HTTP response contains  custom header on both web-01 and web-02
var=$(hostname)
new_string="error_page 404 \/custom_404.html;\n location \/redirect_me {\n return 301 \$scheme:\/\/www.google.com;"
new_string2="http {\n\tadd_header X-Served-By $var;"

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^http \{/$new_string2/" /etc/nginx/nginx.conf
sudo service nginx start