#!/usr/bin/env bash
# Configure a new Ubuntu machine to have Nginx server

host=$(hostname)
apt-get -y update
apt-get -y install nginx
echo "server {
    listen 80 default_server;

    location / {
        add_header X-Served-By $host;
    }
}" >/etc/nginx/sites-available/default
sudo service nginx restart