#!/usr/bin/env bash
# Configures new Ubuntu machine to install and configure HAProxy

sudo apt-get -y update
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get install haproxy=2.0.\* -y

echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg
printf %s "
  frontend haproxy
      bind *:80
      mode http
      default_backend web_servers

  backend web_servers
    mode http
    balance roundrobin
    server 243213-web-01 54.88.227.197:80 check
    server 243213-web-02 34.207.83.201:80 check
" | sudo tee /etc/haproxy/haproxy.cfg > dev/null

sudo service haproxy start