#!/bin/bash

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 243213-web-01 54.88.227.197:80 check
    server 243213-web-02 34.207.83.201:80 check
EOT

# Enable and start HAproxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy