#!/usr/bin/env bash
#a  script that pings an IP address passed as an argument

IP="${1}"

# filename variable
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	echo "Usage: ${fn} {IP_ADDRESS}"
else
	ping -c 5 "${IP}"
fi
