#!/usr/bin/env bash
# Makes sure that Nginx is running on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
kill -9 "$(cat /var/run/nginx.pid)"
